

###
curl -X POST https://demoaisearch241016.search.windows.net/datasources?api-version=2020-06-30 -H "Content-Type: application/json" -H "api-key: r8llfOngzUQuH8vemC2TU6W5nM9LSuquSPwhygAJRrAzSeD3RZqR" -d @data_source.json


###
curl -X PUT https://demoaisearch241016.search.windows.net/skillsets/margies-custom-skillset?api-version=2020-06-30 -H "Content-Type: application/json" -H "api-key: Ipvhlx13u6IqdaTatBealb8b7OQNRJUNAdqZB4dmxtAzSeCIa7Ln" -d @skillset.json

###
curl -X PUT https://demoaisearch241016.search.windows.net/indexes/margies-custom-index?api-version=2020-06-30 -H "Content-Type: application/json" -H "api-key: r8llfOngzUQuH8vemC2TU6W5nM9LSuquSPwhygAJRrAzSeD3RZqR" -d @index.json

###
curl -X PUT https://demoaisearch241016.search.windows.net/indexers/margies-custom-indexer?api-version=2020-06-30 -H "Content-Type: application/json" -H "api-key: r8llfOngzUQuH8vemC2TU6W5nM9LSuquSPwhygAJRrAzSeD3RZqR" -d @indexer.json
